#ifndef ESP_AVB_CONFIG_H_
#define ESP_AVB_CONFIG_H_

// Extended configuration options for ESP_AVB
#define CONFIG_ESP_AVB_ASSOCIATION_ID 0x0000000000000000 // uint64_t
#define CONFIG_ESP_AVB_PORT_ID 0x0001 // uint16_t
#define CONFIG_ESP_AVB_ENTITY_NAME "Simple Talker"
#define CONFIG_ESP_AVB_VENDOR_NAME "ACME"
#define CONFIG_ESP_AVB_MODEL_NAME "ESP_AVB Simple Talker"
#define CONFIG_ESP_AVB_GROUP_NAME ""
#define CONFIG_ESP_AVB_FIRMWARE_VERSION "1.0.0"
#define CONFIG_ESP_AVB_SERIAL_NUMBER ""
#define CONFIG_ESP_AVB_INTERFACE_NAME "AVB Interface"
#define CONFIG_ESP_AVB_STREAM_FORMAT 0x0205021800406000 // uint64_t (AAF, 24/48, 32bit)

#endif /* ESP_AVB_CONFIG_H_ */