name: Upload component
on:
  push:
    branches: [ main ]

jobs:
  upload_components:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout
      - uses: espressif/upload-components-ci-action
        with:
          components: "esp_avb: ."
          namespace: "scrambletools"
